language: go
os:
  - linux
  - osx
go:
  - 1.13.x
go_import_path: github.com/kataras/methodoverride
env:
 global:
   - GO111MODULE=on
install:
  - go get ./...
script:
  - go test -v -cover ./...
